apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredesk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredesk-app
  template:
    metadata:
      labels:
        app: coredesk-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: oss02
      containers:
        - name: coredesk-app
          image: jackcranee/sluopenproject-oss:0.0.1
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/coredesk"
            - name: JWT_SECRET
              value: "slu-secret-key-2026"
            - name: AWS_ACCESS_KEY_ID
              value: "minio-admin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minio-secret"
---
apiVersion: v1
kind: Service
metadata:
  name: coredesk-service
spec:
  type: NodePort
  selector:
    app: coredesk-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
